# paths
TRAINING_DATASET_PATH = 'D:\\ML\\th\\datasets\\480p'
TEST_DATASET_PATH = 'D:\\ML\\th\\datasets\\test_1080'

# preprocessing parameters
TRAINING_IMAGES_SIZE = 270
IMAGE_DIFF_MAX_THRESHOLD = 3000
IMAGE_DIFF_MIN_THRESHOLD = 22
IMAGE_MIN_VARIANCE_THRESHOLD = 8
MAX_FLOW = 6
IMAGES_WINDOW_SIZE = 1

# training parameters
TRAINING_TOTAL_SAMPLES = 10000000
TENSORBOARD_LOG_INTERVAL = 10000
BATCH_SIZE = 10

# debug
VERBOSE_MODE = True
TRAINING_PROGRESS_BAR_LENGTH = 10
SHOW_TEST_SAMPLES_INFO_ON_LOAD = True
TENSORBOARD_ROOT_DIR = 'tensorboard'
MODEL_ID = 'unet_inceptionGAN_v1'
TENSORBOARD_RUN_DIR = '{}\\{}'.format(TENSORBOARD_ROOT_DIR, MODEL_ID)
MAX_MODELS_TO_KEEP = 1
