# training parameters
TRAINING_TOTAL_SAMPLES = 10000000
TENSORBOARD_LOG_INTERVAL = 2500

# misc
TRAINING_DATASET_PATH = 'D:\\ML\\th\\datasets\\480p'
TEST_DATASET_PATH = 'D:\\ML\\th\\datasets\\test_1080'
IMAGE_DIFF_MAX_THRESHOLD = 3000
IMAGE_DIFF_MIN_THRESHOLD = 20
BATCH_SIZE = 4

# debug
VERBOSE_MODE = True
TRAINING_PROGRESS_BAR_LENGTH = 10
SHOW_TEST_SAMPLES_INFO_ON_LOAD = True
TENSORBOARD_ROOT_DIR = 'tb'
MODEL_ID = 'simple_cnn_v3'
TENSORBOARD_RUN_DIR = '{}\\{}'.format(TENSORBOARD_ROOT_DIR, MODEL_ID)
MAX_MODELS_TO_KEEP = 1
