# training parameters
TRAINING_TOTAL_ITERATIONS = 1000000
TENSORBOARD_LOG_INTERVAL = 1000

# misc
TRAINING_DATASET_PATH = 'D:\\ML\\th\\datasets\\480p'
SOURCE_PATH = 'Z:\\TV Series'
IMAGE_DIFF_MAX_THRESHOLD = 1000
IMAGE_DIFF_MIN_THRESHOLD = 25
BATCH_SIZE = 48

# debug
VERBOSE_MODE = True
TENSORBOARD_DIR = 'tb'
