# training parameters
TRAINING_TOTAL_ITERATIONS = 1000000
TENSORBOARD_LOG_INTERVAL = 250

# misc
TRAINING_DATASET_PATH = 'D:\\ML\\th\\datasets\\480p'
TEST_DATASET_PATH = '{}\\test'.format(TRAINING_DATASET_PATH)
SOURCE_PATH = 'Z:\\TV Series'
IMAGE_DIFF_MAX_THRESHOLD = 4000
IMAGE_DIFF_MIN_THRESHOLD = 20
BATCH_SIZE = 12

# debug
VERBOSE_MODE = True
SHOW_TEST_SAMPLES_INFO_ON_LOAD = True
TENSORBOARD_ROOT_DIR = 'tb'
MODEL_ID = 'simple_cnn_v2'
TENSORBOARD_RUN_DIR = '{}\\{}'.format(TENSORBOARD_ROOT_DIR, MODEL_ID)
MAX_MODELS_TO_KEEP = 1
